filebeat.prospectors:
  - input.type: log
    pipeline: "ng-log-pipeline"
    paths:
      - /home/app_billing/applications/purchase-gateway/stage/logs/purchase-gateway.log
    fields:
      type: "log"
  - input.type: log
    pipeline: "ng-event-pipeline"
    paths:
      - /home/app_billing/applications/purchase-gateway/stage/logs/purchase-gateway-events.log
    fields:
      type: "event"
  - input.type: log
    pipeline: "ng-worker-pipeline"
    paths:
      - /home/app_billing/applications/purchase-gateway/stage/logs/purchase-gateway-worker.log
    fields:
      type: "worker"

setup.template.enabled: false
setup.template.overwrite: false

processors:
  - drop_fields:
      fields: ["offset", "beat.name", "beat.version"]

output.elasticsearch:
  hosts: ["ded639.ded.reflected.net:9200"]
  compression_level: 9
  worker: 3
  index: "ng-stage-logs-%{[fields.type]:other}-%{+yyyy.MM.dd}"