version: '3.7'

networks:
  default:
    name: ng-network

services:
  web:
    image: harbor.mgcorp.co/probiller/probiller-ng/php:7.3.5-grpc-1.35-v1
    container_name: purchase-gateway-web
    environment:
      - OPCACHE_ENABLED=0
      - XDEBUG_ENABLED=1
      - PUBSUB_EMULATOR_HOST=host.docker.internal:8085
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/keyFile.json
      - PHP_IDE_CONFIG=serverName=localhost
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=host.docker.internal
    volumes:
    - type: bind
      source: ./
      target: /var/www/html
    - type: volume
      source: app_logs
      target: /var/www/html/lumen/storage/logs
    - type: bind
      source: ./entrypoint.sh
      target: /docker-entrypoint.d/10-entrypoint.sh
    - type: bind
      source: ./lumen/config/supervisor/supervisor_develop.conf
      target: /etc/supervisor/conf.d/develop.conf
    - type: bind
      source: ./docs
      target: /var/www/html/lumen/public/docs
    - type: bind
      source: "${GOOGLE_APPLICATION_CREDENTIALS}"
      target: /tmp/keys/keyFile.json
    depends_on:
      - database
    ports:
      - 8008:80
      - 9008:9001 #supervisor web port

  database:
    image: harbor.mgcorp.co/probiller/probiller-ng/mysql
    container_name: purchase-gateway-database
    ports:
      - 3333:3306
    environment:
      - MYSQL_DATABASE=ng_purchase_gateway

volumes:
  app_logs:
    external: true
  event_logs:
    external: true
