<?php
/**
 * Service Api Clients configuration
 */
return [
    'fraud'                 => [
        'apiKeys'           => env('FRAUD_API_KEYS', []),
        'apiKeyPrefixes'    => env('FRAUD_API_KEYS_PREFIXES', []),
        'accessToken'       => env('FRAUD_ACCESS_TOKEN', ''),
        'username'          => env('FRAUD_USERNAME', ''),
        'password'          => env('FRAUD_PASSWORD', ''),
        'host'              => env('FRAUD_HOST', 'http://localhost'),
        'userAgent'         => env('FRAUD_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('FRAUD_DEBUG', false),
        'debugFile'         => env('FRAUD_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('FRAUD_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('FRAUD_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('FRAUD_TIMEOUT', 5)
    ],
    'memberProfileGateway'  => [
        'apiKeys'           => env('MEMBER_PROFILE_GATEWAY_API_KEYS', []),
        'apiKeyPrefixes'    => env('MEMBER_PROFILE_GATEWAY_API_KEYS_PREFIXES', []),
        'accessToken'       => env('MEMBER_PROFILE_GATEWAY_ACCESS_TOKEN', ''),
        'username'          => env('MEMBER_PROFILE_GATEWAY_USERNAME', ''),
        'password'          => env('MEMBER_PROFILE_GATEWAY_PASSWORD', ''),
        'host'              => env('MEMBER_PROFILE_GATEWAY_HOST', 'http://localhost'),
        'userAgent'         => env('MEMBER_PROFILE_GATEWAY_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('MEMBER_PROFILE_GATEWAY_DEBUG', false),
        'debugFile'         => env('MEMBER_PROFILE_GATEWAY_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('MEMBER_PROFILE_GATEWAY_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('MEMBER_PROFILE_GATEWAY_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('MEMBER_PROFILE_GATEWAY_TIMEOUT', 5)
    ],
    'binRouting'            => [
        'apiKeys'           => env('BIN_ROUTING_API_KEYS', []),
        'apiKeyPrefixes'    => env('BIN_ROUTING_API_KEYS_PREFIXES', []),
        'accessToken'       => env('BIN_ROUTING_ACCESS_TOKEN', ''),
        'username'          => env('BIN_ROUTING_USERNAME', ''),
        'password'          => env('BIN_ROUTING_PASSWORD', ''),
        'host'              => env('BIN_ROUTING_HOST', 'http://localhost'),
        'userAgent'         => env('BIN_ROUTING_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('BIN_ROUTING_DEBUG', false),
        'debugFile'         => env('BIN_ROUTING_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('BIN_ROUTING_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('BIN_ROUTING_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('BIN_ROUTING_TIMEOUT', 5)
    ],
    'billerMapping'         => [
        'apiKeys'           => env('BILLER_MAPPING_API_KEYS', []),
        'apiKeyPrefixes'    => env('BILLER_MAPPING_API_KEYS_PREFIXES', []),
        'accessToken'       => env('BILLER_MAPPING_ACCESS_TOKEN', ''),
        'username'          => env('BILLER_MAPPING_USERNAME', ''),
        'password'          => env('BILLER_MAPPING_PASSWORD', ''),
        'host'              => env('BILLER_MAPPING_HOST', 'http://localhost'),
        'userAgent'         => env('BILLER_MAPPING_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('BILLER_MAPPING_DEBUG', false),
        'debugFile'         => env('BILLER_MAPPING_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('BILLER_MAPPING_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('BILLER_MAPPING_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('BILLER_MAPPING_TIMEOUT', 5)
    ],
    'cascadeService'        => [
        'apiKeys'           => env('CASCADE_API_KEYS', []),
        'apiKeyPrefixes'    => env('CASCADE_API_KEYS_PREFIXES', []),
        'accessToken'       => env('CASCADE_ACCESS_TOKEN', ''),
        'username'          => env('CASCADE_USERNAME', ''),
        'password'          => env('CASCADE_PASSWORD', ''),
        'host'              => env('CASCADE_HOST', 'http://localhost'),
        'userAgent'         => env('CASCADE_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('CASCADE_DEBUG', false),
        'debugFile'         => env('CASCADE_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('CASCADE_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('CASCADE_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('CASCADE_TIMEOUT', 5)
    ],
    'transaction'           => [
        'apiKeys'           => env('TRANSACTION_API_KEYS', []),
        'apiKeyPrefixes'    => env('TRANSACTION_API_KEYS_PREFIXES', []),
        'accessToken'       => env('TRANSACTION_ACCESS_TOKEN', ''),
        'username'          => env('TRANSACTION_USERNAME', ''),
        'password'          => env('TRANSACTION_PASSWORD', ''),
        'host'              => env('TRANSACTION_HOST', 'http://localhost'),
        'userAgent'         => env('TRANSACTION_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('TRANSACTION_DEBUG', false),
        'debugFile'         => env('TRANSACTION_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('TRANSACTION_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('TRANSACTION_CONNECTION_TIMEOUT', 15),
        'timeout'           => (int) env('TRANSACTION_TIMEOUT', 95)
    ],
    'emailService'          => [
        'username'          => env('EMAIL_SERVICE_USERNAME', ''),
        'password'          => env('EMAIL_SERVICE_PASSWORD', ''),
        'host'              => env('EMAIL_SERVICE_HOST', ''),
        'userAgent'         => env('EMAIL_SERVICE_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('EMAIL_SERVICE_DEBUG', false),
        'debugFile'         => env('EMAIL_SERVICE_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('EMAIL_SERVICE_TEMP_FOLDER_PATH', ''),
        'aadAuth'           => [
            'clientId'     => env('EMAIL_SERVICE_AAD_CLIENT_ID', ''),
            'tenant'       => env('EMAIL_SERVICE_AAD_TENANT', ''),
            'clientSecret' => env('EMAIL_SERVICE_AAD_CLIENT_SECRET', ''),
            'resource'     => env('EMAIL_SERVICE_AAD_CLIENT_RESOURCE', ''),
        ],
        'connectionTimeout' => (int) env('EMAIL_SERVICE_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('EMAIL_SERVICE_TIMEOUT', 5)
    ],
    'paymentTemplate'       => [
        'apiKeys'           => env('PAYMENT_TEMPLATE_API_KEYS', []),
        'apiKeyPrefixes'    => env('PAYMENT_TEMPLATE_API_KEYS_PREFIXES', []),
        'accessToken'       => env('PAYMENT_TEMPLATE_ACCESS_TOKEN', ''),
        'username'          => env('PAYMENT_TEMPLATE_USERNAME', ''),
        'password'          => env('PAYMENT_TEMPLATE_PASSWORD', ''),
        'host'              => env('PAYMENT_TEMPLATE_HOST', 'http://localhost'),
        'userAgent'         => env('PAYMENT_TEMPLATE_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('PAYMENT_TEMPLATE_DEBUG', false),
        'debugFile'         => env('PAYMENT_TEMPLATE_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('PAYMENT_TEMPLATE_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('PAYMENT_TEMPLATE_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('PAYMENT_TEMPLATE_TIMEOUT', 5)
    ],
    'fraudServiceCs'        => [
        'username'          => env('FRAUD_SERVICE_CS_USERNAME', ''),
        'password'          => env('FRAUD_SERVICE_CS_PASSWORD', ''),
        'host'              => env('FRAUD_SERVICE_CS_HOST', 'http://localhost'),
        'userAgent'         => env('FRAUD_SERVICE_CS_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('FRAUD_SERVICE_CS_DEBUG', false),
        'debugFile'         => env('FRAUD_SERVICE_CS_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('FRAUD_SERVICE_CS_TEMP_FOLDER_PATH', ''),
        'aadAuth'           => [
            'clientId'     => env('FRAUD_SERVICE_CS_AAD_CLIENT_ID', ''),
            'tenant'       => env('FRAUD_SERVICE_CS_AAD_TENANT', ''),
            'clientSecret' => env('FRAUD_SERVICE_CS_AAD_CLIENT_SECRET', ''),
            'resource'     => env('FRAUD_SERVICE_CS_AAD_CLIENT_RESOURCE', ''),
        ],
        'connectionTimeout' => (int) env('FRAUD_SERVICE_CS_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('FRAUD_SERVICE_CS_TIMEOUT', 5)
    ],
    'adviceNotification'    => [
        'apiKeys'           => env('ADVICE_NOTIFICATION_API_KEYS', []),
        'apiKeyPrefixes'    => env('ADVICE_NOTIFICATION_API_KEYS_PREFIXES', []),
        'accessToken'       => env('ADVICE_NOTIFICATION_ACCESS_TOKEN', ''),
        'username'          => env('ADVICE_NOTIFICATION_USERNAME', ''),
        'password'          => env('ADVICE_NOTIFICATION_PASSWORD', ''),
        'host'              => env('ADVICE_NOTIFICATION_HOST', 'http://localhost'),
        'userAgent'         => env('ADVICE_NOTIFICATION_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('ADVICE_NOTIFICATION_DEBUG', false),
        'debugFile'         => env('ADVICE_NOTIFICATION_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('ADVICE_NOTIFICATION_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('ADVICE_NOTIFICATION_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('ADVICE_NOTIFICATION_TIMEOUT', 5)
    ],
    'bundleManagementAdmin' => [
        'apiKeys'           => env('BUNDLE_MANAGEMENT_API_KEYS', []),
        'apiKeyPrefixes'    => env('BUNDLE_MANAGEMENT_API_KEYS_PREFIXES', []),
        'accessToken'       => env('BUNDLE_MANAGEMENT_ACCESS_TOKEN', ''),
        'username'          => env('BUNDLE_MANAGEMENT_USERNAME', ''),
        'password'          => env('BUNDLE_MANAGEMENT_PASSWORD', ''),
        'host'              => env('BUNDLE_MANAGEMENT_HOST', 'http://localhost'),
        'userAgent'         => env('BUNDLE_MANAGEMENT_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('BUNDLE_MANAGEMENT_DEBUG', false),
        'debugFile'         => env('BUNDLE_MANAGEMENT_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('BUNDLE_MANAGEMENT_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('BUNDLE_MANAGEMENT_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('BUNDLE_MANAGEMENT_TIMEOUT', 5)
    ],
    'siteAdmin'             => [
        'apiKeys'           => env('SITE_ADMIN_API_KEYS', []),
        'apiKeyPrefixes'    => env('SITE_ADMIN_API_KEYS_PREFIXES', []),
        'accessToken'       => env('SITE_ADMIN_ACCESS_TOKEN', ''),
        'username'          => env('SITE_ADMIN_USERNAME', ''),
        'password'          => env('SITE_ADMIN_PASSWORD', ''),
        'host'              => env('SITE_ADMIN_HOST', 'http://localhost'),
        'userAgent'         => env('SITE_ADMIN_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'             => env('SITE_ADMIN_DEBUG', false),
        'debugFile'         => env('SITE_ADMIN_DEBUG_FILE', 'php://output'),
        'tempFolderPath'    => env('SITE_ADMIN_TEMP_FOLDER_PATH', ''),
        'connectionTimeout' => (int) env('SITE_ADMIN_CONNECTION_TIMEOUT', 5),
        'timeout'           => (int) env('SITE_ADMIN_TIMEOUT', 5)
    ],
    'fraudService'          => [
        'username'       => env('FRAUD_SERVICE_USERNAME', ''),
        'password'       => env('FRAUD_SERVICE_PASSWORD', ''),
        'host'           => env('FRAUD_SERVICE_HOST', 'http://localhost'),
        'userAgent'      => env('FRAUD_SERVICE_USER_AGENT', 'OpenAPI-Generator/1.0.0/PHP'),
        'debug'          => env('FRAUD_SERVICE_DEBUG', false),
        'debugFile'      => env('FRAUD_SERVICE_DEBUG_FILE', 'php://output'),
        'tempFolderPath' => env('FRAUD_SERVICE_TEMP_FOLDER_PATH', ''),
    ],
    'eventIngestionSystem' => [
        'host'                      => env('EVENT_INGESTION_SERVICE_CS_HOST', ''),
        'test'                      => env('EVENT_INGESTION_SERVICE_CS_TEST_EVENTS', true),
        'client_id'                 => env('FRAUD_SERVICE_CS_AAD_CLIENT_ID', ''),
        'tenant'                    => env('FRAUD_SERVICE_CS_AAD_TENANT', ''),
        'resource'                  => env('FRAUD_SERVICE_CS_AAD_CLIENT_RESOURCE', ''),
        'client_secret'             => env('FRAUD_SERVICE_CS_AAD_CLIENT_SECRET', ''),
        'maxNumberOfAttempts'       => 10,
        'delayBeforeRetryInSeconds' => 3,
    ],

    'configService' => [
        'host'          => env('CONFIG_SERVICE_HOST', 'localhost:5000'),
        'aadAuth' => [
            'clientId'     => env('CONFIG_SERVICE_AAD_CLIENT_ID', ''),
            'tenant'        => env('CONFIG_SERVICE_AAD_TENANT', ''),
            'resource'      => env('CONFIG_SERVICE_AAD_CLIENT_RESOURCE', ''),
            'clientSecret' => env('CONFIG_SERVICE_AAD_CLIENT_SECRET', ''),
        ]
    ],
    'mgpg'        => [
        'aadAuth'           => [
            'clientId'     => env('MGPG_AAD_CLIENT_ID', ''),
            'clientSecret' => env('MGPG_AAD_CLIENT_SECRET', ''),
            'env'          => env('MGPG_HOST_NAME', ''),
            'resource'     => env('MGPG_AAD_RESOURCE', '')
        ],
    ],
];
